spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=30m
  jpa:
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        ddl-auto: update
    show-sql: false
  threads:
    virtual:
      enabled: true
  mail:
    host: "${ACCOUNTABILITY_EMAIL_HOST:smtp.gmail.com}"
    port: ${ACCOUNTABILITY_EMAIL_PORT:587}
    username: "${ACCOUNTABILITY_EMAIL_ADDRESS:example@gmail.com}"
    password: "${ACCOUNTABILITY_EMAIL_PASSWORD:accountability-pw}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: "${DB_JDBC_URL:jdbc:postgresql://localhost:5432/database}"
    username: "${DB_USER:accountability}"
    password: "${DB_PASSWORD:accountability-pw}"
    hikari:
      driver-class-name: org.postgresql.Driver

logging:
  file:
    path: "./logs"
    name: "./logs/accountability.log"
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 100MB
      clean-history-on-start: true
  level:
    com.github.holly: INFO

application:
  base-url: "${APPLICATION_BASE_URL:http://localhost:8080}"

